# Generated by Django 2.2.4 on 2019-08-17 22:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=4, max_digits=5)),
                ('change_1d', models.DecimalField(decimal_places=4, max_digits=5)),
                ('change_1w', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
